name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Run tests
        run: go test

      - name: Generate Sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the containe registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            gmarinho21/nlw.journey.api:${{ steps.generate_sha.outputs.sha}}
            gmarinho21/nlw.journey.api:latest

    - name: Update image helm
      uses: fjogeleit/yaml-update-action@main
      with:
        branch: release
        targetBranch: main
        createPR: true
        valueFile: 'deploy/values.yaml'
        propertyPath: 'image.tag'
        value: ${{ steps.generate_sha.outputs.sha }}
        commitChange: true
        message: "[skip ci] Update tag in values helm"